# Generated by Django 5.2.4 on 2025-09-10 02:11

import django.db.models.deletion
import leads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('scheduler', '0016_aluno_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_interessado', models.CharField(max_length=255, verbose_name='Nome do Interessado')),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável (se aplicável)')),
                ('contato', models.CharField(help_text='Telefone ou E-mail', max_length=100)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, help_text='Ex: Instagram, Indicação, etc.', max_length=100, null=True, verbose_name='Fonte do Lead')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações e Histórico')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('negociando', 'Negociando'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno_convertido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origem', to='scheduler.aluno')),
                ('unidade_negocio', models.ForeignKey(default=leads.models.get_escola_unidade_negocio, on_delete=django.db.models.deletion.PROTECT, to='core.unidadenegocio')),
            ],
        ),
    ]
