# Generated by Django 5.2.4 on 2025-09-10 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação Telefônica'), ('email', 'E-mail'), ('whatsapp', 'Mensagem (WhatsApp)'), ('visita', 'Visita Presencial'), ('outro', 'Outro')], default='ligacao', max_length=20, verbose_name='Tipo de Interação')),
                ('notas', models.TextField(verbose_name='Anotações')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='leads.lead')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação do Lead',
                'verbose_name_plural': 'Interações do Lead',
                'ordering': ['-data_interacao'],
            },
        ),
    ]
