# Generated by Django 5.2.4 on 2025-09-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_interacaolead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='curso_interesse',
            field=models.CharField(blank=True, choices=[('bateria', 'Bateria'), ('percussao', 'Percussão'), ('musicalizacao', 'Musicalização Infantil'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Curso de Interesse'),
        ),
        migrations.AddField(
            model_name='lead',
            name='melhor_horario_contato',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã (08:00 - 12:00)'), ('tarde', 'Tarde (14:00 - 17:00)'), ('noite', 'Noite (18:00 - 21:00)')], max_length=50, null=True, verbose_name='Melhor Horário para Contato'),
        ),
        migrations.AddField(
            model_name='lead',
            name='nivel_experiencia',
            field=models.CharField(blank=True, choices=[('iniciante', 'Iniciante (nunca toquei)'), ('basico', 'Básico (já tive algum contato)'), ('intermediario', 'Intermediário (toco por hobby)'), ('avancado', 'Avançado (busco aperfeiçoamento)')], max_length=50, null=True, verbose_name='Nível de Experiência'),
        ),
    ]
