# Generated by Django 5.2.4 on 2025-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_curso_interesse_lead_melhor_horario_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='motivo_interesse_especifico',
            field=models.TextField(blank=True, null=True, verbose_name='3. Algo em específico que te fez interessar pela bateria?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='objetivo_tocar',
            field=models.TextField(blank=True, null=True, verbose_name='2. Onde você gostaria de tocar?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='proposito_estudo',
            field=models.TextField(blank=True, null=True, verbose_name='1. Qual seu propósito de estudar bateria?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sobre_voce',
            field=models.TextField(blank=True, null=True, verbose_name='3.1 Conte um pouco sobre você'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='curso_interesse',
            field=models.CharField(blank=True, choices=[('batera_facil', 'Batera no Fácil'), ('teclado', 'Teclado'), ('personalizado_batucada', 'Personalizado Batucada'), ('mentoria_black_batucada', 'Mentoria Black Batucada'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Curso de Interesse'),
        ),
    ]
