# Generated by Django 5.2.4 on 2025-09-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_motivo_interesse_especifico_lead_objetivo_tocar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='curso_interesse',
            field=models.CharField(blank=True, choices=[('batera_facil', 'Batera no Fácil'), ('personalizado_batucada', 'Personalizado Batucada'), ('mentoria_black_batucada', 'Mentoria Black Batucada'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Curso de Interesse'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='motivo_interesse_especifico',
            field=models.TextField(blank=True, null=True, verbose_name='Algo em específico que te fez interessar pela bateria?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='objetivo_tocar',
            field=models.TextField(blank=True, null=True, verbose_name='Onde você gostaria de tocar?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='proposito_estudo',
            field=models.TextField(blank=True, null=True, verbose_name='Qual seu propósito de estudar bateria?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sobre_voce',
            field=models.TextField(blank=True, null=True, verbose_name='Conte um pouco sobre você'),
        ),
    ]
