# Generated by Django 5.2.4 on 2025-10-02 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_curso_interesse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
