# Generated by Django 5.2.4 on 2025-10-02 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Data de Criação'),
        ),
    ]
