# Generated by Django 5.2.4 on 2025-11-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_data_criacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='convertido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_convertidos', to=settings.AUTH_USER_MODEL, verbose_name='Convertido por'),
        ),
        migrations.AddField(
            model_name='lead',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
