# Generated by Django 5.2.4 on 2025-11-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_convertido_por_lead_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='curso_interesse',
            field=models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('batera_facil', 'Batera no Fácil'), ('canto', 'Canto'), ('guitarra', 'Guitarra'), ('mentoria_black_batucada', 'Mentoria Black Batucada'), ('outro', 'Outro'), ('personalizado_batucada', 'Personalizado Batucada'), ('teclado', 'Teclado')], max_length=50, null=True, verbose_name='Curso de Interesse'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='melhor_horario_contato',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã (08:00 - 12:00)'), ('tarde', 'Tarde (14:00 - 17:00)'), ('noite', 'Noite (18:00 - 21:00)')], max_length=50, null=True, verbose_name='Horário da Aula'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('negociando', 'Negociando'), ('perdido', 'Perdido')], default='novo', max_length=20),
        ),
    ]
