# Generated by Django 5.2.4 on 2025-09-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_de_produto', to='core.unidadenegocio')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU / Cód. de Barras')),
                ('quantidade_em_estoque', models.PositiveIntegerField(default=0, verbose_name='Qtd. em Estoque')),
                ('custo_de_aquisicao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de Aquisição')),
                ('percentual_markup', models.DecimalField(decimal_places=2, default=40.0, help_text='Percentual de lucro desejado sobre o custo.', max_digits=5, verbose_name='Markup (%)')),
                ('preco_de_venda_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda Manual (Opcional)')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categoriaproduto')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.unidadenegocio')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
