# Generated by Django 5.2.4 on 2025-09-07 06:41

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=1024)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=200)),
                ('resource_id', models.CharField(blank=True, max_length=255)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='logs_auditl_timesta_630212_idx'), models.Index(fields=['user'], name='logs_auditl_user_id_67b1a3_idx'), models.Index(fields=['action'], name='logs_auditl_action_84dba6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='logs_auditl_resourc_52fc75_idx')],
            },
        ),
    ]
