# Generated by Django 5.2.4 on 2025-08-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['professor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Professor Relacionado'),
        ),
    ]
