# Generated by Django 5.2.4 on 2025-08-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finances', '0002_transaction_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unidade_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.unidadenegocio'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unidade_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.unidadenegocio'),
        ),
    ]
