# Generated by Django 5.2.4 on 2025-08-28 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finances', '0003_category_unidade_negocio_transaction_unidade_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_competencia', models.DateField(verbose_name='Mês de Competência')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('a_pagar', 'A Pagar'), ('pago', 'Pago')], default='a_pagar', max_length=10)),
                ('categoria', models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, to='finances.category')),
                ('transacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transaction')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.unidadenegocio')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_competencia', models.DateField(verbose_name='Mês de Competência')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data do Recebimento')),
                ('status', models.CharField(choices=[('a_receber', 'A Receber'), ('recebido', 'Recebido')], default='a_receber', max_length=10)),
                ('categoria', models.ForeignKey(limit_choices_to={'type': 'income'}, on_delete=django.db.models.deletion.PROTECT, to='finances.category')),
                ('transacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.transaction')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='core.unidadenegocio')),
            ],
        ),
    ]
