# Generated by Django 5.2.4 on 2025-08-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_despesa_receita'),
        ('scheduler', '0015_aluno_cpf_aluno_responsavel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='scheduler.aluno', verbose_name='Aluno Relacionado'),
        ),
    ]
