# Generated by Django 5.2.4 on 2025-08-28 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finances', '0006_despesa_professor'),
        ('scheduler', '0016_aluno_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_do_mes', models.PositiveIntegerField(verbose_name='Dia do Mês para Lançamento')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Início da Recorrência')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Recorrência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Está ativa?')),
                ('categoria', models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, to='finances.category')),
                ('professor', models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['professor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_recorrentes', to=settings.AUTH_USER_MODEL)),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_recorrentes', to='core.unidadenegocio')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_do_mes', models.PositiveIntegerField(verbose_name='Dia do Mês para Lançamento')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Início da Recorrência')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Recorrência')),
                ('ativa', models.BooleanField(default=True, verbose_name='Está ativa?')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_recorrentes', to='scheduler.aluno')),
                ('categoria', models.ForeignKey(limit_choices_to={'type': 'income'}, on_delete=django.db.models.deletion.PROTECT, to='finances.category')),
                ('unidade_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_recorrentes', to='core.unidadenegocio')),
            ],
        ),
    ]
