# Generated by Django 5.2.4 on 2025-08-31 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_despesarecorrente_receitarecorrente'),
        ('scheduler', '0016_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitarecorrente',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas_recorrentes', to='scheduler.aluno'),
        ),
        migrations.AlterField(
            model_name='receitarecorrente',
            name='dia_do_mes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dia do Mês para Lançamento'),
        ),
        migrations.AlterField(
            model_name='receitarecorrente',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
