# Generated by Django 5.2.4 on 2025-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_receitarecorrente_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tipo_dre',
            field=models.CharField(choices=[('custo', 'Custo Direto'), ('despesa', 'Despesa Operacional')], default='despesa', help_text="Classifique como 'Custo' se for diretamente ligado à venda/serviço, ou 'Despesa' para gastos gerais.", max_length=10, verbose_name='Classificação no DRE'),
        ),
    ]
