# Generated by Django 5.2.4 on 2025-09-04 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_category_tipo_dre'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='store.produto', verbose_name='Produto Relacionado'),
        ),
        migrations.AddField(
            model_name='receita',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Quantidade Vendida'),
        ),
    ]
