# Generated by Django 6.0.1 on 2026-01-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_receita_produto_receita_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('especie', 'Espécie'), ('transferencia', 'Transferência'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
