# Generated by Django 5.2.4 on 2025-07-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAula',
            fields=[
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.aula')),
                ('exercicios_rudimentos', models.TextField(blank=True, null=True, verbose_name='Exercícios de Rudimentos')),
                ('bpm_rudimentos', models.CharField(blank=True, max_length=100, null=True, verbose_name='BPM dos Rudimentos')),
                ('exercicios_ritmo', models.TextField(blank=True, null=True, verbose_name='Exercícios de Ritmo')),
                ('livro_ritmo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Livro/Método de Ritmo')),
                ('clique_ritmo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clique/BPM do Ritmo')),
                ('exercicios_viradas', models.TextField(blank=True, null=True, verbose_name='Exercícios de Viradas')),
                ('clique_viradas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clique/BPM das Viradas')),
                ('repertorio_musicas', models.TextField(blank=True, null=True, verbose_name='Músicas do Repertório')),
                ('observacoes_gerais', models.TextField(blank=True, null=True, verbose_name='Observações Gerais sobre a Aula')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aula',
            name='observacoes',
        ),
    ]
