# Generated by Django 5.2.4 on 2025-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_relatorioaula_remove_aula_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioaula',
            name='conteudo_teorico',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Teórico Abordado'),
        ),
    ]
