# Generated by Django 5.2.4 on 2025-07-04 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_relatorioaula_conteudo_teorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioaula',
            name='professor_que_validou',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_validadas_por_mim', to=settings.AUTH_USER_MODEL, verbose_name='Professor que Realizou a Aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Professor Atribuído'),
        ),
    ]
