# Generated by Django 5.2.4 on 2025-07-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_relatorioaula_professor_que_validou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto de Perfil'),
        ),
    ]
