# Generated by Django 5.2.4 on 2025-07-05 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioaula',
            name='bpm_rudimentos',
        ),
        migrations.RemoveField(
            model_name='relatorioaula',
            name='clique_ritmo',
        ),
        migrations.RemoveField(
            model_name='relatorioaula',
            name='clique_viradas',
        ),
        migrations.RemoveField(
            model_name='relatorioaula',
            name='exercicios_ritmo',
        ),
        migrations.RemoveField(
            model_name='relatorioaula',
            name='exercicios_rudimentos',
        ),
        migrations.RemoveField(
            model_name='relatorioaula',
            name='exercicios_viradas',
        ),
        migrations.RemoveField(
            model_name='relatorioaula',
            name='livro_ritmo',
        ),
        migrations.CreateModel(
            name='ItemRitmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Exercício')),
                ('livro_metodo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Livro/Método')),
                ('bpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clique/BPM')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ritmo', to='scheduler.relatorioaula')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRudimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Exercício')),
                ('bpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='BPM')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_rudimentos', to='scheduler.relatorioaula')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Exercício')),
                ('bpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clique/BPM')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_viradas', to='scheduler.relatorioaula')),
            ],
        ),
    ]
