# Generated by Django 5.2.4 on 2025-07-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_relatorioaula_bpm_rudimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemritmo',
            name='duracao_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='itemrudimento',
            name='duracao_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
        migrations.AddField(
            model_name='itemvirada',
            name='duracao_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
    ]
