# Generated by Django 5.2.4 on 2025-07-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_itemritmo_duracao_min_itemrudimento_duracao_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.aluno', verbose_name='Aluno'),
        ),
    ]
