# Generated by Django 5.2.4 on 2025-07-08 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_aula_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='professor',
        ),
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='aulas', to='scheduler.aluno', verbose_name='Alunos'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo__in': ['professor', 'admin']}, related_name='aulas_lecionadas', to=settings.AUTH_USER_MODEL, verbose_name='Professores Atribuídos'),
        ),
    ]
