# Generated by Django 5.2.4 on 2025-07-08 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_aula_aluno_remove_aula_professor_aula_alunos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='aulas_aluno', to='scheduler.aluno', verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo__in': ['admin', 'professor']}, related_name='aulas_lecionadas', to=settings.AUTH_USER_MODEL, verbose_name='Professores Atribuídos'),
        ),
    ]
