# Generated by Django 5.2.4 on 2025-07-11 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_aula_alunos_alter_aula_professores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação/Matrícula'),
        ),
        migrations.CreateModel(
            name='PresencaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='scheduler.aula')),
            ],
            options={
                'unique_together': {('aula', 'aluno')},
            },
        ),
    ]
