# Generated by Django 5.2.4 on 2025-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_aluno_data_criacao_presencaaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemritmo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='itemrudimento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='itemvirada',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='relatorioaula',
            name='observacoes_repertorio',
            field=models.TextField(blank=True, null=True, verbose_name='Observações sobre o Repertório'),
        ),
        migrations.AddField(
            model_name='relatorioaula',
            name='observacoes_teoria',
            field=models.TextField(blank=True, null=True, verbose_name='Observações sobre a Teoria'),
        ),
    ]
