# Generated by Django 5.2.4 on 2025-07-13 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_itemritmo_observacoes_itemrudimento_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_professores', to='scheduler.aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aula', 'professor')},
            },
        ),
    ]
