# Generated by Django 5.2.4 on 2025-08-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_presencaprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dia_vencimento',
            field=models.PositiveIntegerField(blank=True, help_text='Dia do mês para o vencimento da mensalidade (ex: 5, 10, 15).', null=True, verbose_name='Dia do Vencimento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='valor_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor da Mensalidade'),
        ),
    ]
