# Generated by Django 5.2.4 on 2025-08-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_aluno_dia_vencimento_aluno_valor_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel_nome',
            field=models.CharField(blank=True, help_text='Preencher caso o aluno seja menor de idade.', max_length=255, null=True, verbose_name='Nome do Responsável'),
        ),
    ]
