# Generated by Django 5.2.4 on 2025-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_aluno_cpf_aluno_responsavel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('trancado', 'Trancado')], default='ativo', max_length=10, verbose_name='Status'),
        ),
    ]
