# Generated by Django 5.2.4 on 2025-09-12 02:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_aluno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='tipo_pagamento',
            field=models.CharField(choices=[('aula', 'Por Aula (Valor Fixo)'), ('aluno', 'Por Aluno (Valor por Presença)')], default='aula', help_text='Define se o pagamento é um valor fixo por aula ou multiplicado pelo número de alunos presentes.', max_length=10, verbose_name='Método de Cálculo do Pagamento'),
        ),
        migrations.AddField(
            model_name='modalidade',
            name='valor_pagamento_professor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor padrão pago ao professor.', max_digits=10, verbose_name='Valor do Pagamento por Aula/Aluno'),
        ),
    ]
