# Generated by Django 5.2.4 on 2025-09-24 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_modalidade_tipo_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(help_text="Um identificador único para o tour, ex: 'horarios_fixos_v1'", max_length=100)),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tour_id')},
            },
        ),
    ]
