# Generated by Django 5.2.4 on 2025-09-24 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_tourvisto'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencaaluno',
            name='aula_reposicao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aula_reposta_de', to='scheduler.aula', verbose_name='Aula de Reposição Agendada'),
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='tipo_falta',
            field=models.CharField(blank=True, choices=[('injustificada', 'Injustificada'), ('justificada', 'Justificada')], default='injustificada', max_length=15, null=True, verbose_name='Tipo de Falta'),
        ),
    ]
