# Generated by Django 5.2.4 on 2025-09-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_presencaaluno_aula_reposicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='status',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada'), ('Aluno Ausente', 'Aluno Ausente'), ('Reposta', 'Reposta')], default='Agendada', max_length=20),
        ),
    ]
