# Generated by Django 5.2.4 on 2025-11-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_alter_aula_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('professor', 'Professor'), ('comercial', 'Comercial')], default='professor', max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
