# Generated by Django 5.2.4 on 2025-11-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_alter_modalidade_options_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
    ]
