# Generated by Django 6.0 on 2025-12-12 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioaula',
            name='ultimo_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_editados', to=settings.AUTH_USER_MODEL, verbose_name='Última Edição Por'),
        ),
    ]
